# ----------- CONFIGURABLE START -----------
title:            "mrozo - home page"
description:      "electronics, coding, hacking"
url:              https://mrozo.pl # Site url, without a slash at the end.
signoff:          "mrozo" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons
plugins:
  - jekyll-feed

links:
  - name:         Articles
    url:          /articles.html
    external:     false
  - name:         About me
    url:          /
    external:     false
  - name:         RSS
    url:          /feed.xml
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
